name: Typo Report
description: Find a typo ? You are at the right place !
title: "Typo: "
labels: [ typo ]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to this Typo Report !

  - type: input
    id: typo
    attributes:
      label: Typo
      description: What is the typo you find?
      placeholder: I loves bread
    validations:
      required: true

  - type: input
    id: answer
    attributes:
      label: Answer
      description: What is the correct way to write it?
      placeholder: I love bread
    validations:
      required: true


  - type: input
    id: command
    attributes:
      label: Command
      description: Which command did you run to have this typo?
      placeholder: /exercice
    validations:
      required: true

  - type: dropdown
    id: lang
    attributes:
      label: Lang
      description: Which lang has the problem ?
      multiple: true
      options:
        - French
        - Spanish
    validations:
      required: true
